name: tdd
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1

  equatable: ^2.0.3

  flutter_bloc: ^8.0.1

  get_it: ^7.2.0

  http: ^0.13.3

  rxdart: ^0.27.3
  injectable: ^2.5.0
  injectable_generator: ^2.7.0
  http_interceptor: ^1.0.2

dev_dependencies:

  bloc_test: ^9.0.2

  build_runner: ^2.1.2

  flutter_test:

   sdk: flutter

  mockito: ^5.0.15

  mocktail: ^0.2.0

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

